# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0002_kon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='vid',
            old_name='post',
            new_name='user',
        ),
    ]
