# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0003_auto_20170404_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quize.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='vid',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kon',
            name='vid',
        ),
        migrations.DeleteModel(
            name='Vid',
        ),
        migrations.AddField(
            model_name='kon',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quize.Category'),
            preserve_default=False,
        ),
    ]
