# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0004_auto_20170404_2028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kon',
            new_name='Contest',
        ),
    ]
