# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0006_auto_20170405_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(choices=[('sport', 'Спортивные'), ('tvor', 'Творческие'), ('intel', 'Интеллектуальные')], max_length=1),
        ),
    ]
