# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0008_auto_20170405_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(choices=[('1', 'Magazine'), ('2', 'Radio Station'), ('3', 'Journal'), ('4', 'TV Station'), ('5', 'Newspaper'), ('6', 'Website')], max_length=200),
        ),
    ]
