# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0009_auto_20170405_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(choices=[('Спортивные', 'Спортивные'), ('Интеллектуальные', 'Интеллектуальные'), ('Творческие', 'Творческие')], max_length=200),
        ),
    ]
